variables:
    LIBFABRIC_DIR: "/global/cfs/cdirs/m1248/pdc/libfabric-1.12.1/install"
    MERCURY_DIR: "/global/cfs/cdirs/m1248/pdc/mercury-2.0.0/install"
    PDC_BUILD_PATH: "${CI_PROJECT_DIR}/build"
    PDC_INSTALL_PATH: "${CI_PROJECT_DIR}/install"
    
stages:
    - build
    - test

build-cori:
    stage: build
    tags:
        - cori
    variables:
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
    script:
        - module list
        - mkdir -p ${PDC_BUILD_PATH}/cori
        - cd ${PDC_BUILD_PATH}/cori
        - cmake ../.. -DBUILD_MPI_TESTING=ON -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DPDC_ENABLE_MPI=ON -DPDC_ENABLE_TIMING=ON -DMERCURY_DIR=$MERCURY_DIR -DCMAKE_C_COMPILER=cc -DCMAKE_C_FLAGS=-dynamic -DMPI_RUN_CMD=srun -DPDC_ENABLE_LUSTRE=ON -DPDC_DISABLE_CHECKPOINT=ON -DCMAKE_INSTALL_PREFIX=${PDC_INSTALL_PATH}/cori
        - make -j
        - make install
    artifacts:
        paths:
            - ${PDC_BUILD_PATH}/cori
            - ${PDC_INSTALL_PATH}/cori
      
test-cori:
    tags:
        - cori
    variables:
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
    script:        
        - export LD_LIBRARY_PATH="$LIBFABRIC_DIR/lib:$MERCURY_DIR/lib:$LD_LIBRARY_PATH"
        - cd ${PDC_BUILD_PATH}/cori
        - ctest -L parallel
